version: "3"
services:
  postgres:
    container_name: postgres_container_serverless-challenge
    image: postgres
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    restart: unless-stopped

  app:
    container_name: serverless-challenge
    build:
      context: ./
      target: development
      dockerfile: Dockerfile
      args:
        NODE_VERSION: '18.12'
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
